### ISSUE TITLE
add CircleCI tests

### ISSUE THREAD

**Issue by picatz** [picatz/doh#4]
It'd be nice to catch when/if any of the implemented sources have a random change or is acting flakey. Probably should add something like [CircleCI](https://circleci.com/).

For example, the [`quad9`](https://github.com/picatz/doh/blob/master/core/sources/quad9.go) source seems to be erring out from a TLS handshake timeout which can be seen when using `--verbose`:

```
error: Get https://dns.quad9.net/dns-query?name=google.com&type=A: net/http: TLS handshake timeout
```

After looking at their documentation and using the example link, this url seems to actually work: 
```
https://dns.quad9.net:5053/dns-query?name=google.com&type=A
```
Removing the `:5053` port part I see the following plaintext error on the web page:
```
Unable to find the DNS parameter
```

I don't really know when this change occurred, but it would've been nice to catch earlier. 🤷‍♂ 

> **Note**: I plan on fixing the `quad9` source so it doesn't error anymore.

**Comment by correabuscar** [comment]
Looks like if you strip port 5053 then you have to pass (only) `?dns=` argument,
eg. `https://9.9.9.9/dns-query?dns=AAABAAABAAAAAAAAA3d3dwdleGFtcGxlA2NvbQAAAQAB` which is base64 of some kind of binary request for `www.example.com` and the result is a file that Firefox(in my case) auto downloads, 49 bytes, binary reply like:
```
$ cat dns-query\(1\) |od  -tcu1x1
0000000  \0  \0 201 200  \0 001  \0 001  \0  \0  \0  \0 003   w   w   w
          0   0 129 128   0   1   0   1   0   0   0   0   3 119 119 119
         00  00  81  80  00  01  00  01  00  00  00  00  03  77  77  77
0000020  \a   e   x   a   m   p   l   e 003   c   o   m  \0  \0 001  \0
          7 101 120  97 109 112 108 101   3  99 111 109   0   0   1   0
         07  65  78  61  6d  70  6c  65  03  63  6f  6d  00  00  01  00
0000040 001 300  \f  \0 001  \0 001  \0  \0   a   %  \0 004   ] 270 330
          1 192  12   0   1   0   1   0   0  97  37   0   4  93 184 216
         01  c0  0c  00  01  00  01  00  00  61  25  00  04  5d  b8  d8
0000060   "
         34
         22
0000061
```

as per doc: https://datatracker.ietf.org/doc/html/rfc8484#section-4.1.1



I guess they're using 5053 because the input arguments and the result is plaintext only, as per https://quad9.net/news/blog/doh-with-quad9-dns-servers/
> https://9.9.9.9:5053/dns-query?name=quad9.net
Updated 7/25/2019 – This is now running on a custom port since this implementation is not inline with the most recent standards based DoH implementation. (see RFC 8484)

(note: I didn't read the RFC)
